# UPDATE SAU
services:
  mariadb:
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g

  minio:
    restart: always

  backend:
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MINIO_PUBLIC_ENDPOINT: ${MINIO_PUBLIC_ENDPOINT}
    deploy:
      resources:
        limits:
          memory: 1g

  frontend:
    restart: always
    ports:
      - "${HTTP_PORT:-8000}:8000"
