export enum NavIconEnum {
  Brand = 'description',
  Menu = 'menu',
  Account = 'account_circle',
  Logout = 'logout',
  Home = 'home',
  Departments = 'account_tree',
  People = 'people',
  Teams = 'groups',
  Password = 'lock_reset',
  Profiles = 'badge',
  AddCv = 'note_add',
  Deleted = 'delete_history',
  Person = 'person',
  PendingActions = 'pending_actions',
  ApprovalQueue = 'fact_check',
}