import { LanguageProficiency } from "../enums/language-proficiency.enum";
import { ProficiencyLevel } from "../enums/proficiency-level.enum";

/*
 * Wire shape of content_json, mirroring the backend records. Keys stay snake_case because a
 * published version is immutable: renaming a key here would stop old versions from being read.
 * 
 * - item_id is generated by the backend on creation and never changes. It anchors inline comments,
 * keys the diff between two versions and matched entries across languages of the same profile.
 */
export interface RepeatedEntry {
    item_id: string;
    display_order: number;
    is_untranslated: boolean;
    deleted_in_master: boolean;
}

export interface PersonalInfo {
    full_name: string | null;
    date_of_birth: string | null;
    email: string | null;
    phone: string | null;
    address: string | null;
    position: string | null;
}

export interface CareerObjective {
    content: string | null;
}

export interface SkillEntry extends RepeatedEntry {
    skill_id: string | null;
    skill_name: string | null;
    proficiency: ProficiencyLevel | null;
    note: string | null;
}

export interface ExperienceEntry extends RepeatedEntry {
    company: string | null;
    position: string | null;
    start_date: string | null;
    end_date: string | null;
    description: string | null;
}

export interface EducationEntry extends RepeatedEntry {
    institution: string | null;
    degree: string | null;
    field: string | null;
    start_date: string | null;
    end_date: string | null;
    description: string | null;
}

export interface CertificationEntry extends RepeatedEntry {
    name: string | null;
    issuing_organization: string | null;
    issue_date: string | null;
    expiry_date: string | null;
    credential_id: string | null;
}

export interface ProjectEntry extends RepeatedEntry {
    name: string | null;
    role: string | null;
    team_size: number | null;
    start_date: string | null;
    end_date: string | null;
    description: string | null;
    technologies: string[];
}

export interface LanguageEntry extends RepeatedEntry {
    language_name: string | null;
    proficiency: LanguageProficiency | null;
    certification: string | null;
}

export interface AdditionalInfoEntry extends RepeatedEntry {
    title: string | null;
    content: string | null;
}

// The whole content_json of a draft or a published version.
export interface CvContent {
    personal_info: PersonalInfo;
    career_objective: CareerObjective;
    skills: SkillEntry[];
    experience: ExperienceEntry[];
    education: EducationEntry[];
    certifications: CertificationEntry[];
    projects: ProjectEntry[];
    languages: LanguageEntry[];
    additional_info: AdditionalInfoEntry[];
}

// Client-side skeleton, used before the first save round-trip.
export function emptyCvContent(): CvContent {
    return {
        personal_info: {
            full_name: null, date_of_birth: null, email: null,
            phone: null, address: null, position: null,
        },
        career_objective: { content: null },
        skills: [],
        experience: [],
        education: [],
        certifications: [],
        projects: [],
        languages: [],
        additional_info: [],
    }
}