spring.application.name=CVManagementBE
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# -------- Server --------
server.servlet.context-path=/api

# -------- SpringDoc --------
springdoc.swagger-ui.path=/docs

