package com.training.cvmanagementbe.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;

// Shown once in the admin dialog; also delivered in the email to the user
@Schema(name = "ResetPasswordResponse", description = "Response containing temporary password generated by admin reset")
public record ResetPasswordResponse(
        @Schema(example = "Temp#987654")
        String temporaryPassword
) {
}
